### ISSUE TITLE
oscillatorNode.start(undefined) throws an error in Chrome but not in web-audio-test-api

### ISSUE THREAD

**Issue by benji6** [mohayonao/web-audio-test-api#29]
It's a bit of a niche case but `new AudioContext().createOscillator().start(undefined)` throws an error in Chrome but not in web-audio-test-api or in Firefox actually... It caught me out so I'm wondering if maybe in the spirit of keeping this testing framework strict it should check whether undefined was passed in and if so then throw an error?

**Comment by mohayonao** [comment]
oh.. Chrome..
I didn't consider those cases.
I'll check and fix this issue.

thanks

**Comment by benji6** [comment]
This is awesome, thanks
