### ISSUE TITLE
AudioBufferSourceNode detune param not implemented

### ISSUE THREAD

**Issue by danigb** [mohayonao/web-audio-test-api#31]
I'm trying to test some code that uses the detune k-param of AudioBufferedSourceNode (https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune) and it fails.

It's currently a working draft, but it works on Chrome (I can hear it ;-) 

If you agree, and I finally understand how params works, I try to make a PR.

**Comment by mohayonao** [comment]
thanks! I've updated it.

**Comment by danigb** [comment]
Great! Thanks
